spring:
  application:
    name: ai-chat
server:
  port: 8080
ai:
  credentials:
    models:
      deepseek:
        api-key: sk-dfd1b213dafa47958e4476501e1cc11b
        base-url: https://api.deepseek.com/chat/completions
      openai:
        api-key: sk-test
        base-url: https://api.openai.com